### ISSUE TITLE
todo v1

### ISSUE THREAD

**Issue by mkg20001** [mgit-at/nix-unify#1]
- [x] linking of files and db for removal
  - keep track of which links are from nix
  - if user-created file exist at target then bail
- [x] linking via ~~function~~ hooks
  - so that modules can do their post-linking magic right away
- [ ] merge files
  - feature for files hook to add merge flag, merge strategy and comment type
  - will allow to merge files like /etc/systemd/system.conf instead of replacing them
- [x] merge users
  - users that exist in nixos but not in host should be created
  - groups and group memberships aswell
  - track which users, groups, memberships are from nixos and remove them once they get removed in nixos / update them (shell, etc) when they get changed
  - add/replace the literal entries line by line
- [x] run as systemd generator
  - will pollute the host less (easier to uninstall)
  - we no longer need to enable and start everything as that will be done for us
- [ ] proper file backup
  - when replacing a file from the host rename to $FILE.nix-unify
  - and store path for later restoration on uninstall-

- [x] share nftables
  - optional
  - force flushRuleset to false
  - nftables service works in a way that is non-desturbing
- [x] share networkd
  - all or nothing (there is no default config by default)
- [x] share serviecs
  - service by service
  - also take service-dependencies into account
  - skip services which already exist on the host unless forced
- [ ] share sudoers
  - optional
  - include nixos sudoers config (maybe without defaults)
- [x] share etc
  - optional
  - file by file (or folder by folder) inclusion

- [ ] use systemd-run, locking, etc like upstream
- [x] handle service-restart, triggers, etc
- [ ] split into activation and switch parts
  - currently the script is an organically grown mess
